language: node_js
node_js:
  - "7"
# safelist
branches:
  only:
    - master
    - stable
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project shit-experience --token $FIREBASE_TOKEN
